CREATE DATABASE IF NOT EXISTS resto_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON resto_app.* TO 'user'@'%';
FLUSH PRIVILEGES;
